= K2, a kernel for embedded C++ projects

> Time is a powerful thing, if you know how to use it.

== What this claims to be
*K2 is a small real-time C++ task manager that unapologetically refers to its central object as "Kernel", despite making no claim to operating systems, privilege rings, or academic rigor.*

It exists to enqueue work, dequeue it deterministically, and get out of the way. Built by an autodidact with more curiosity than credentials and a preference for things that are simple, explicit, and fast over things that are fashionable.

*100% Human Written Code*

=== To do

.Things I would like to add/change before I make critical decisions on the version numbers
* Error system with reporting and handling capabilities
* Currently, K2 has no chill on the execution stack. It needs optimization.
* A test suite

== Example

.Prints a mundane message, slowly.
[source,c++]
----
#include <chrono>
#include <stdio.h>
#include <cstring>

#include <K2>

// Very high precision nanosecond rtc for x86_64, will probably
// not work on other platforms.
uint64_t time_ns64()
{
    return std::chrono::duration_cast<std::chrono::nanoseconds>(
               std::chrono::high_resolution_clock::now().time_since_epoch())
        .count();
}

// Prints a message, slowly.
class ExampleTask : public K2::Kernel::Task
{
private:
    uint8_t _pos = 0;
    size_t _len = 0;
    const char *_message = "Hello, world!\n";
    const uint64_t _delay = 333e6; // = 333ms

    void Initialize() override
    {
        _len = std::strlen(_message);
    }

    void Payload() override
    {
        printf("%c", _message[_pos++]);
        fflush(stdout);
        if (_pos == _len)
            End();
        else
            DelayNanoseconds(_delay);
    }
};

int main(int, char **)
{
    auto k2krnl = new K2::Kernel(time_ns64, 1);

    auto example = new ExampleTask();
    k2krnl->GetSchedule()->Load(example);

    while (k2krnl->GetSchedule()->Count())
        k2krnl->Cycle();

    delete (example);
    delete (k2krnl);

    return 0;
}
----


